Update database version number + Destructive Migration
                                                                                                    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: 520d0c3d8036d3fe64b7791efeca3bae, found: b03a982d869187463a8365c3059f66c0